agile_components:
    features:
        - name: account_recovery
            enabled: False
        - name: audit_logging
            enabled: False
        - name: captcha_recaptcha
            enabled: False
        - name: multi_factor_authentication
            enabled: False
        - name: oauth2_and_social_login
            enabled: False
        - name: passwordless_login
            enabled: False
        - name: role_based_access_control
            enabled: False
        - name: user_registration
            enabled: False
        - name: custom_reports
            enabled: False
        - name: geolocation_services
            enabled: False
        - name: order_tracking_and_history
            enabled: False
        - name: payment_integration
            enabled: False
        - name: scheduler_and_calendar
            enabled: False
        - name: shopping_cart_and_checkout
            enabled: False
        - name: subscription_management
            enabled: False
        - name: user_behavior_tracking
            enabled: False
        - name: wishlist
            enabled: False
        - name: background_tasks
            enabled: False
        - name: caching
            enabled: False
        - name: image_optimization
            enabled: False
        - name: progressive_web_app
            enabled: False
        - name: admin_dashboard
            enabled: False
        - name: content_recommendations
            enabled: False
        - name: customizable_layout
            enabled: False
        - name: dark_mode_and_light_mode
            enabled: False
        - name: drag_and_drop
            enabled: False
        - name: header_and_footer
            enabled: False
        - name: in_app_feedback
            enabled: False
        - name: interactive_maps
            enabled: False
        - name: live_chat
            enabled: False
        - name: multi_language_support
            enabled: False
        - name: offline_mode
            enabled: False
        - name: onboarding_and_tutorials
            enabled: False
        - name: push_notifications
            enabled: False
        - name: rich_media_support
            enabled: False
        - name: search_and_filter
            enabled: False
        - name: social_sharing
            enabled: False
        - name: user_profiles
            enabled: False
    labels:
        - name: High
          description: Highest priority
          color: fd0000
        - name: Medium
          description: 
          color: fd7d0b
        - name: Low
          description: Lowest priority
          color: f9cb17
        - name: Feature
          description: Implement a new feature
          color: 00bd34
        - name: Enhancement
          description: Improve an existing feature
          color: 0df38b
        - name: Bug
          description: Report incorrect or unexpected behavior
          color: f90fe5
        - name: Technical Task
          description: Set ups, deployments, DevOps
          color: 9f9f9f
        - name: Documentation
          description: Updating and Maintaining the documentation
          color: f3f3f3
        - name: Testing
          description: Everything related to testing
          color: 9b04d7
        - name: Epic
          description: Big achievements toward our goal
          color: b02768
        - name: User Story
          description: Should be handled over a sprint
          color: f37c9d
        - name: ~ Front-End ~
          description: Task with a focus on front-end development
          color: ffffff
        - name: ~  Back-End ~
          description: Task with a focus on back-end development
          color: "101011"
    milestones:
        - name: UX Design
          due_date: 2024-11-01 18:00:00
          path_to_body:
            - agile_components
            - milestones
            - ux.txt
        - name: Minimum Viable Product
          due_date: 2024-11-11 18:00:00
          path_to_body:
            - agile_components
            - milestones
            - mvp.txt
        - name: First Enhancement
          due_date: 2024-12-12 18:00:00
          path_to_body:
            - agile_components
            - milestones
            - first_enhancement.txt
        - name: Fix Bugs + Production deployments
          due_date: 2024-12-31 18:00:00
          path_to_body:
            - agile_components
            - milestones
            - first_release.txt